# Generated by Django 4.1.3 on 2022-12-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('describition', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Seen', 'Seen')], max_length=50)),
                ('notification_type', models.CharField(choices=[('Web', 'Web'), ('Web', 'Web'), ('Web', 'Web')], max_length=70)),
                ('senting_time', models.DateField(auto_now=True)),
                ('created_At', models.DateField(auto_now=True)),
            ],
        ),
    ]
