# Generated by Django 4.1.3 on 2022-12-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Web', 'Web'), ('android', 'android'), ('iphone', 'iphone')], max_length=70),
        ),
    ]
