# Generated by Django 4.1.3 on 2023-01-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('location', models.TextField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.TextField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(null=True)),
                ('collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seconetomanay.collage')),
            ],
        ),
    ]
