# Generated by Django 4.1.3 on 2022-12-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0002_remove_company_emplyees_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created',
        ),
    ]
