# Generated by Django 4.1.3 on 2023-01-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0003_remove_company_created_remove_employee_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
