# Generated by Django 4.1.3 on 2023-01-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0004_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
